<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Hash\" />
    <Folder Include="Jwt\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lente.Domain\Lente.Domain.csproj" />
    <ProjectReference Include="..\Lente.Infraestruture\Lente.Infraestruture.csproj" />
  </ItemGroup>

</Project>
